health_man_sys/config/routes.rb
Rails.application.routes.draw do

  get 'appointments/index'

  get 'welcome/index'

  get 'patient/index'

  get 'doctors/index'

  get 'records/index'

  resources :patients, :doctors, :records, :appointments

  resources :patients do
    resources :appointments
  end

  resources :doctors do
    resources :patients
  end

  resources :patients do
    resources :records
  end

  resources :doctors do
    resources :records
  end

  root 'welcome#index'
end

health_man_sys/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

health_man_sys/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

health_man_sys/app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :patients, dependent: :destroy
  has_many :records, through: :patients, dependent: :destroy
  has_many :appointments
  validates :first_name, presence: true
  validates :surname, presence: true
  validates :phone_no, presence: true
  validates :speciality, presence: true
end

health_man_sys/app/models/patient.rb
class Patient < ApplicationRecord
  has_and_belongs_to_many :doctors
  has_many :records
  has_and_belongs_to_many :appointments
  validates :first_name, presence: true
  validates :surname, presence: true
  validates :date_of_birth, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true
end

health_man_sys/app/models/record.rb
class Record < ApplicationRecord
  belongs_to :patient
  has_and_belongs_to_many :doctors
  has_one :appointment
end

health_man_sys/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

health_man_sys/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :find_appointment, only: [:show, :edit, :update, :destroy]

  def index
    @appointment = Appointment.all.order("created_at DESC")
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)

    if @appointment.save
      redirect_to @appointment
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment
    else
      render 'edit'
    end
  end

  def destroy
    @appointment.destroy
    redirect_to root_path
  end

  private
    def appointment_params
      params.require(:appointment).permit(:date, :time, :doctor)
    end
end

health_man_sys/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :find_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctor = Doctor.all.order("created_at DESC")
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to @doctor
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor
    else
      render 'edit'
    end
  end

  def destroy
    @doctor.destroy
    redirect_to root_path
  end

  private
    def find_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:first_name, :surname, :phone_no, :speciality)
    end
end

health_man_sys/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :find_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patient = Patient.all.order("created_at DESC")
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient
    else
      render 'edit'
    end
  end

  def destroy
    @patient.destroy
    redirect_to root_path
  end

  private
    def find_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :surname, :date_of_birth, :address, :phone_no, :medical_card, :medical_insurance)
    end
end

health_man_sys/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :find_record, only: [:show, :edit, :update, :destroy]

  def index
    @record = Record.all.order("created_at DESC")
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)

    if @record.save
      redirect_to @record
    else
      render 'new'
    end
  end

  def show
    @record = Record.find(params[:id])
  end

  def edit
  end

  def update
    if @record.update(record_params)
      redirect_to @record
    else
      render 'edit'
    end
  end

  def destroy
    @record.destroy
    redirect_to root_path
  end

  private
    def find_record
      @record = Record.find(params[:id])
    end

    def record_params
      params.require(:record).permit(:appointment_time, :doctor_id, :observation, :previous_condition, :treatment, :referral_letter, :blood_test, :sick_note, :perscription)
    end
end

health_man_sys/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

health_man_sys/app/helpers/application_helper.rb
module ApplicationHelper
end

health_man_sys/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

health_man_sys/app/helpers/doctors_helper.rb
module DoctorsHelper
end

health_man_sys/app/helpers/patients_helper.rb
module PatientsHelper
end

health_man_sys/app/helpers/records_helper.rb
module RecordsHelper
end

health_man_sys/app/helpers/welcome_helper.rb
module WelcomeHelper
end

health_man_sys/app/views/appointments/_form.html.erb
<%= form_for @appointment do |f| %>
  <p>
    <%= f.label :date %> <%= f.date_field :date %>
  </p>
  <p>
    <%= f.label :time %> <%= f.time_field :time %>
  </p>
  <br />
  <%= f.submit %>
<% end %><br />

health_man_sys/app/views/appointments/edit.html.erb
<h1>Edit Appointment Details</h1>

<%= render 'form' %>

health_man_sys/app/views/appointments/index.html.erb
<h1>Appointments#index</h1>
<p>Find me in app/views/appointments/index.html.erb</p>

health_man_sys/app/views/appointments/new.html.erb
<h1>Enter New Appointment Details</h1>

<%= render 'form' %>

health_man_sys/app/views/appointments/show.html.erb
<div class="appointment-details">
  <h1>Appointment Details</h1>
  <p><strong>Date:</strong> <%= @appointment.date %></p>
  <p><strong>Time:</strong> <%= @appointment.time %></p>
  <p><strong>Doctor:</strong> <%= @appointment.doctor %></p>
  <small><%= link_to "Back", appointments_path %> <%= link_to "Edit Appointment Details", edit_appointment_path(@appointment) %></small>
  <small><%= link_to "Delete Appointment", appointment_path(@appointment), method: :delete, data: { confirm: "Are you sure?" } %></small>
</div>

health_man_sys/app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name %><br />
  <br />
  <%= f.label :surname %><br />
  <%= f.text_field :surname %><br />
  <br />
  <%= f.label :phone_no %><br />
  <%= f.text_field :phone_no %><br />
  <br />
  <%= f.label :speciality %><br />
  <%= f.text_area :speciality %><br />
  <br />
  <%= f.submit %>
<% end %>

health_man_sys/app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>

<%= render 'form' %>

health_man_sys/app/views/doctors/index.html.erb
<h1>List of Doctors in this Clinic</h1>
<% @doctor.each do |doctor| %>
  <div class="doctor-names">
      <h3><%= doctor.first_name %> <%= doctor.surname %> <small><%= link_to "Full details", doctor %></small></h3>
  </div>
<% end %>

health_man_sys/app/views/doctors/new.html.erb
<h1>Enter Doctor Details</h1>

<%= render 'form' %>

health_man_sys/app/views/doctors/show.html.erb
<div class="doctor-details">
  <h1>Name: <%= @doctor.first_name %> <%= @doctor.surname %></h1>
  <p><strong>Phone No.:</strong> <%= @doctor.phone_no %></p>
  <p><strong>Speciality:</strong> <%= @doctor.speciality %></p>
  <small><%= link_to "Back", doctors_path %> <%= link_to "Edit Doctor Details", edit_doctor_path(@doctor) %></small>
  <small><%= link_to "Delete Doctor", doctor_path(@doctor), method: :delete, data: { confirm: "Are you sure?" } %></small>
</div>

health_man_sys/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Health Management System</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav">
      <div class="home">
        <%= link_to "Home", root_path %>
      </div>
      <div class="patient-list">
        <%= link_to "Patients", patients_path %>
      </div>
      <div class="add-patient">
        <%= link_to "Add Patient", new_patient_path %>
      </div>
      <div class="doctor-list">
        <%= link_to "Doctors", doctors_index_path %>
      </div>
      <div class="add-doctor">
        <%= link_to "Add Doctor", new_doctor_path %>
      </div>
      <div class="record-list">
        <%= link_to "Records", records_index_path %>
      </div>
      <div class="add-record">
        <%= link_to "Add Record", new_record_path %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

health_man_sys/app/views/patients/_form.html.erb
<%= form_for @patient do |f| %>
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name %><br />
  <br />
  <%= f.label :surname %><br />
  <%= f.text_field :surname %><br />
  <br />
  <%= f.label :date_of_birth %><br />
  <%= f.date_field :date_of_birth %><br />
  <br />
  <%= f.label :address %><br />
  <%= f.text_area :address %><br />
  <br />
  <%= f.label :phone_no %><br />
  <%= f.text_field :phone_no %><br />
  <br />
  <%= f.label :medical_card %><br />
  <%= f.check_box :medical_card %><br />
  <br />
  <%= f.label :medical_insurance %><br />
  <%= f.text_field :medical_insurance %><br />
  <br />
  <%= f.submit %>
<% end %>

health_man_sys/app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= render 'form' %>

health_man_sys/app/views/patients/index.html.erb
<h1>List of Patients</h1>
<% @patient.each do |patient| %>
  <div class="patient-names">
      <h3><%= patient.first_name %> <%= patient.surname %> <small><%= link_to "Full details", patient %></small></h3>
  </div>
<% end %>

health_man_sys/app/views/patients/new.html.erb
<h1>Enter Patient Details</h1>

<%= render 'form' %>

health_man_sys/app/views/patients/show.html.erb
<div class="patient-details">
  <h1>Name: <%= @patient.first_name %> <%= @patient.surname %></h1>
  <p><strong>Date of Birth:</strong> <%= @patient.date_of_birth %></p>
  <p><strong>Address:</strong> <%= @patient.address %></p>
  <p><strong>Phone No.:</strong> <%= @patient.phone_no %></p>
  <p><strong>Medical Card:</strong> <%= @patient.medical_card %></p>
  <p><strong>Medical Insurance:</strong> <%= @patient.medical_insurance %></p>
  <button><%= link_to "Add New Record", new_record_path %></button><button><%= link_to "Show Records", records_path %></button><br><br>
  <button><%= link_to "Add New Appointment", new_appointment_path %></button><br><br>
  <small><%= link_to "Back", patients_path %> <%= link_to "Edit Patient Details", edit_patient_path(@patient) %></small>
  <small><%= link_to "Delete Patient", patient_path(@patient), method: :delete, data: { confirm: "Are you sure?" } %></small>
</div>

health_man_sys/app/views/records/_form.html.erb
<%= form_for @record do |f| %>
  <%= f.label :appointment_time %><br />
  <%= f.datetime_local_field :appointment_time %><br />
  <br />
  <%= f.label :doctor_id %><br />
  <%= f.text_field :doctor %><br />
  <br />
  <%= f.label :observation %><br />
  <%= f.text_area :observation %><br />
  <br />
  <%= f.label :previous_condition %><br />
  <%= f.text_area :previous_condition %><br />
  <br />
  <%= f.label :treatment %><br />
  <%= f.text_area :treatment %><br />
  <br />
  <%= f.label :referral_letter %><br />
  <%= f.text_area :referral_letter %><br />
  <br />
  <%= f.label :blood_test %><br />
  <%= f.check_box :blood_test %><br />
  <br />
  <%= f.label :sick_note %><br />
  <%= f.check_box :sick_note %><br />
  <br />
  <%= f.label :perscription %><br />
  <%= f.text_area :perscription %><br />
  <br />
  <%= f.submit %>
<% end %>

health_man_sys/app/views/records/edit.html.erb
<h1>Edit Record Details</h1>

<%= render 'form' %>

health_man_sys/app/views/records/index.html.erb
<h1>Patient Records</h1>
<% @record.each do |record| %>
    <h3><%= record.appointment_time %><small><%= link_to "Full details", record %></small></h3>
<% end %>

health_man_sys/app/views/records/new.html.erb
<h1>Enter Record Details</h1>

<%= render 'form' %>

health_man_sys/app/views/records/show.html.erb
<div class="patient-records">
  <p><strong>Appointment Date and Time:</strong> <%= @record.appointment_time %></p>
  <p><strong>Doctor:</strong> <%= @record.doctor %></p>
  <p><strong>Observations:</strong> <%= @record.observation %></p>
  <p><strong>Previous Conditions:</strong> <%= @record.previous_condition %></p>
  <p><strong>Treatments:</strong> <%= @record.treatment %></p>
  <p><strong>Referral Letters:</strong> <%= @record.referral_letter %></p>
  <p><strong>Blood Tests:</strong> <%= @record.blood_test %></p>
  <p><strong>Sick Notes:</strong> <%= @record.sick_note %></p>
  <p><strong>Perscriptions:</strong> <%= @record.perscription %></p>
</div>

health_man_sys/app/views/welcome/index.html.erb
<h1>Smart Health Care-Patient Management System</h1>